---
- name: Checking if target project exists on OCP..
  command: oc get project {{ openshift_project }}
  register: getProject
  failed_when: false

- name: Creating target project..
  command: oc new-project {{ openshift_project }}
  failed_when: false
  when: getProject.stdout is search("not found")
