---

- name: Authenticate with OpenShift via user and password
  shell: |
      oc login {{ openshift_host }} \
      -u {{ openshift_user }} \
      -p {{ openshift_password }} \
      --insecure-skip-tls-verify={{ openshift_skip_tls_verify | default(false) | bool }}
  when:
    - openshift_user is defined
    - openshift_password is defined
    - openshift_token is not defined
  no_log: true

- name: Retrieve Access Token ...
  shell: oc whoami -t
  register: ocwhoami
  when:
    - openshift_user is defined
    - openshift_password is defined
    - openshift_token is not defined
  no_log: true

- name: Storing Token ..
  set_fact:
    openshift_token: "{{ ocwhoami.stdout }}"
  when:
    - openshift_user is defined
    - openshift_password is defined
    - openshift_token is not defined
  no_log: true
