---
#Ansible Tower url
ansible_tower_download_url: "https://releases.ansible.com/ansible-tower/setup_openshift/ansible-tower-openshift-setup-{{ ansible_tower_version }}.tar.gz"
ansible_tower_version: 3.8.1-1
# oc clients found at 'https://mirror.openshift.com/pub/openshift-v3/clients/'
ansible_tower_oc_download_url: https://mirror.openshift.com/pub/openshift-v3/clients/3.10.47/linux/oc.tar.gz

##Initial Tower Config
admin_user: 'admin'
admin_password: 'admin'
admin_email: 'root@localhost'
secret_key: 'abcdefghijkx'
#Postgre setup
pg_username: 'pgu'
pg_password: 'pgu'
pg_database: 'tower'
pg_port: '5432'
pg_sslmode: 'prefer'  # set to 'verify-full' for client-side enforced SSL
postgress_activate_wait: "120"

# Openshift Credentials

openshift_host: "https://api.crc.testing:6443"
openshift_skip_tls_verify: "true"
openshift_project: "tower"
#Postgre should relay on PVC, but for the moment we support EmptyDir only
openshift_pg_pvc_name: "postgresql"
openshift_pg_emptydir: "true"
